# Generated by Django 5.0.6 on 2025-03-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default='Other', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
