# Generated by Django 5.1.3 on 2024-12-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadmin', '0002_delete_blog_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mail', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
