# Generated by Django 5.0.6 on 2025-03-12 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
