# Generated by Django 5.0.6 on 2025-03-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0005_invitation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='token',
        ),
    ]
