# Generated by Django 5.0.6 on 2025-03-12 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0006_remove_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
